# Generated by Django 2.2.19 on 2022-11-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(verbose_name='Номер объекта')),
                ('field', models.IntegerField(verbose_name='Номер месторождения')),
                ('income_date', models.DateTimeField(auto_now_add=True, verbose_name='Время появления')),
            ],
        ),
    ]
