# Generated by Django 2.2.19 on 2022-11-23 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_lab'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab', to='objects.Lab', verbose_name='Логи лаборатории')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab', to='objects.Object', verbose_name='Логи объекта')),
            ],
        ),
    ]
