# Generated by Django 2.2.19 on 2022-11-23 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0004_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='field_well',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='oilfield', to='objects.Object', verbose_name='Родительское месторождение'),
        ),
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название скважины'),
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название пласта')),
                ('well_layer', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='oilfield', to='objects.Field', verbose_name='Родиетельская скважина')),
            ],
        ),
    ]
