# Generated by Django 2.2.19 on 2022-11-23 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0005_auto_20221123_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название пласта')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oilfield', to='objects.Well', verbose_name='Пласт')),
            ],
        ),
    ]
