# Generated by Django 2.2.19 on 2022-11-23 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0006_layer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(verbose_name='Тип работы')),
                ('result', models.CharField(max_length=200, verbose_name='Результат работы')),
                ('task_lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskforlab', to='objects.Lab', verbose_name='Работы')),
            ],
        ),
    ]
