# Generated by Django 2.2.19 on 2022-11-23 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('objects', '0007_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='operator',
        ),
        migrations.AddField(
            model_name='lab',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lab', to=settings.AUTH_USER_MODEL, verbose_name='Оператор'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskforlab', to='objects.Lab', verbose_name='Lab'),
        ),
    ]
