# Generated by Django 2.2.19 on 2022-11-24 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0008_auto_20221123_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='OilField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название месторождения')),
            ],
        ),
        migrations.RemoveField(
            model_name='layer',
            name='layer',
        ),
        migrations.RemoveField(
            model_name='well',
            name='well_layer',
        ),
        migrations.AddField(
            model_name='well',
            name='layer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='objects.Layer', verbose_name='Пласт'),
        ),
        migrations.AlterField(
            model_name='object',
            name='field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='object', to='objects.OilField', verbose_name='Номер месторождения'),
        ),
        migrations.AlterField(
            model_name='object',
            name='income_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время получения'),
        ),
        migrations.AlterField(
            model_name='well',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Номер скважины'),
        ),
        migrations.DeleteModel(
            name='Field',
        ),
        migrations.AddField(
            model_name='oilfield',
            name='well',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fileds', to='objects.Well', verbose_name='Скважина'),
        ),
    ]
