# Generated by Django 2.2.19 on 2022-11-24 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0010_remove_object_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labobject',
            name='laboratory',
        ),
        migrations.RemoveField(
            model_name='labobject',
            name='object',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_lab',
        ),
        migrations.DeleteModel(
            name='Lab',
        ),
        migrations.DeleteModel(
            name='LabObject',
        ),
        migrations.DeleteModel(
            name='Object',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
