# Generated by Django 2.2.19 on 2022-11-24 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0011_auto_20221124_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oilfield',
            name='well',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='objects.Well', verbose_name='Скважина'),
        ),
    ]
