# Generated by Django 2.2.19 on 2022-11-24 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0012_auto_20221124_0432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(verbose_name='Номер лаборатории')),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(verbose_name='Номер объекта')),
                ('income_date', models.DateTimeField(verbose_name='Время получения')),
                ('oilfield', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='objects', to='objects.OilField', verbose_name='Номер месторождения')),
            ],
        ),
    ]
