# Generated by Django 2.2.19 on 2022-11-24 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('objects', '0013_lab_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(verbose_name='Тип работы')),
                ('result', models.CharField(max_length=200, verbose_name='Результат работы')),
            ],
        ),
        migrations.CreateModel(
            name='LabObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Время старта работы')),
                ('end_date', models.DateTimeField(auto_now_add=True, verbose_name='Время конца работы')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lab_object', to=settings.AUTH_USER_MODEL, verbose_name='Оператор')),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_object', to='objects.Lab', verbose_name='Логи лаборатории')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_object', to='objects.Object', verbose_name='Логи объекта')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_object', to='objects.Task', verbose_name='Исследование')),
            ],
        ),
    ]
