# Generated by Django 2.2.19 on 2022-11-24 12:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0014_labobject_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='date_of_selection',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата отбора пробы'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='labobject',
            name='laboratory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_object', to='objects.Lab', verbose_name='Лаборатория'),
        ),
        migrations.AlterField(
            model_name='labobject',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_object', to='objects.Object', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='object',
            name='income_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата поступления в лабораторию'),
        ),
    ]
