# Generated by Django 2.2.19 on 2022-11-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0015_auto_20221124_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='income_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата поступления в лабораторию'),
        ),
    ]
