# Generated by Django 2.2.19 on 2022-11-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0017_auto_20221124_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='result_helium',
        ),
        migrations.RemoveField(
            model_name='task',
            name='result_kerosene',
        ),
        migrations.RemoveField(
            model_name='task',
            name='result_kpr',
        ),
        migrations.RemoveField(
            model_name='task',
            name='result_plm',
        ),
        migrations.RemoveField(
            model_name='task',
            name='result_plo',
        ),
        migrations.RemoveField(
            model_name='task',
            name='result_porosity',
        ),
        migrations.RemoveField(
            model_name='task',
            name='result_ues',
        ),
        migrations.RemoveField(
            model_name='task',
            name='result_water',
        ),
        migrations.AddField(
            model_name='task',
            name='result',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Результат'),
        ),
    ]
