# Generated by Django 4.1.3 on 2022-11-24 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0018_auto_20221124_1308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labobject',
            options={'ordering': ('-pk',)},
        ),
    ]
