# Generated by Django 4.1.3 on 2022-11-25 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0019_alter_labobject_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='object',
            options={'ordering': ('-pk',)},
        ),
    ]
