# Generated by Django 4.1.3 on 2022-11-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0020_alter_object_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='link_verge3d',
            field=models.CharField(default='null', max_length=200, verbose_name='Ссылка на 3D Модель'),
            preserve_default=False,
        ),
    ]
