# Generated by Django 4.1.3 on 2023-04-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0021_object_link_verge3d'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='address',
            field=models.CharField(default='a', max_length=200, verbose_name='Адрес лаборатории'),
            preserve_default=False,
        ),
    ]
