# Generated by Django 4.1.3 on 2023-04-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0022_lab_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='carbon_coeff',
            field=models.IntegerField(default=1, verbose_name='Коэфициент карбонатности'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='object',
            name='diameter',
            field=models.IntegerField(default=5, verbose_name='Диаметр(мм)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='object',
            name='gas_value',
            field=models.IntegerField(default=1, verbose_name='Коэффициент газонасыщенности'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='object',
            name='mineral_density',
            field=models.IntegerField(default=10, verbose_name='Минералогическая плотность'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='object',
            name='oil_value',
            field=models.IntegerField(default=5, verbose_name='Коэффициент нефтенасыщенности'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='object',
            name='water_value',
            field=models.IntegerField(default=5, verbose_name='Коэффициент водонасыщенности'),
            preserve_default=False,
        ),
    ]
