# Generated by Django 4.1.3 on 2023-04-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0023_object_carbon_coeff_object_diameter_object_gas_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='carbon_coeff',
            field=models.FloatField(verbose_name='Коэфициент карбонатности'),
        ),
        migrations.AlterField(
            model_name='object',
            name='diameter',
            field=models.FloatField(verbose_name='Диаметр(мм)'),
        ),
        migrations.AlterField(
            model_name='object',
            name='gas_value',
            field=models.FloatField(verbose_name='Коэффициент газонасыщенности'),
        ),
        migrations.AlterField(
            model_name='object',
            name='mineral_density',
            field=models.FloatField(verbose_name='Минералогическая плотность'),
        ),
        migrations.AlterField(
            model_name='object',
            name='oil_value',
            field=models.FloatField(verbose_name='Коэффициент нефтенасыщенности'),
        ),
        migrations.AlterField(
            model_name='object',
            name='water_value',
            field=models.FloatField(verbose_name='Коэффициент водонасыщенности'),
        ),
    ]
