# Generated by Django 4.1.3 on 2023-04-28 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0024_alter_object_carbon_coeff_alter_object_diameter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labobject',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='labobject',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='labobject',
            name='task',
        ),
    ]
