# Generated by Django 4.1.3 on 2023-04-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0025_remove_labobject_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='name',
            field=models.IntegerField(unique=True, verbose_name='Номер объекта'),
        ),
    ]
